image: docker:latest
stages:
  - build
  - deploy

before_script:
  - echo "ENV=production" >> .env
  - echo "COMPOSE_PROJECT_NAME=trulyrichgroup-com" >> .env
  - docker-compose down --remove-orphans

build:
  stage: build
  script:
    - cd src
    - docker-compose build

deploy:
  stage: deploy
  variables:
   CI_DEBUG_TRACE: "true"
  environment:
    name: production
    url: http://docker.trulyrichgroup.com/
  tags:
    - shell
  script:
    - docker-compose down --remove-orphans
    - docker-compose build
    - docker-compose up -d
    - rm -rf .git*
