image: docker:latest
stages:
  - build
  - deploy-container

before_script:
  - echo "WWW_ROOT=/var/www/trulyrichgroup-com" >> .env
  - echo "COMPOSE_PROJECT_NAME=trulyrichgroup" >> .env
  - docker-compose down --remove-orphans
build:
  stage: build
  script:
    - cd src
    - docker-compose build

deploy:container:
  stage: deploy-container
  # variables:
  #  CI_DEBUG_TRACE: "true"
  environment:
    name: production
    url: http://docker.trulyrichgroup.com/
  tags:
    - shell
  script:
    - docker-compose down --remove-orphans
    - docker-compose build
    - docker-compose up -d
    - rm -rf .git*
