image: docker:latest
stages:
  - deploy-container

before_script:
  - echo "ENV=production" >> .env
  - echo "COMPOSE_PROJECT_NAME=trulyrichgroup-com" >> .env

deploy:container:
  image: registry.gitlab.com/gpcentre/trulyrichgroup-com
  stage: deploy-container
  variables:
    CI_DEBUG_TRACE: "true"
  tags:
    - shell
  script:
    - docker-compose up
